### ISSUE TITLE
GoldParagraph data unavailable

### ISSUE THREAD

**Issue by PxYu** [AkariAsai/XORQA#1]
Hi, the link to the GoldParagraph dataset is broken. Can you please update? Thanks!

**Comment by AkariAsai** [comment]
Hi @PxYu , thank you for reporting the issue! I'll update the link in README tomorrow.  The link to the zip file of gold paragraph data is [here](https://nlp.cs.washington.edu/xorqa/XORQA_site/data/xorqa_reading_comprehension_format.zip).

**Comment by PxYu** [comment]
> Hi @PxYu , thank you for reporting the issue! I'll update the link in README tomorrow. The link to the zip file of gold paragraph data is [here](https://nlp.cs.washington.edu/xorqa/XORQA_site/data/xorqa_reading_comprehension_format.zip).

Hi @AkariAsai . I think it is available now. Might be a server error when I reported this. Thanks!
