### ISSUE TITLE
Questions for BM25 baseline

### ISSUE THREAD

**Issue by tomohideshibata** [AkariAsai/XORQA#4]
Thank you for releasing your codes.
I have some questions for BM25.

1. `build_es_simple.py` is described in `baselines/bm25/README.md`, but `build_es.py` is in the repository. `build_es_simple.py` in README.md should be `build_es.py`?

2. The line `from utils import get_analyzer` in `build_es.py` and `es_search_multi.py` should be deleted? (There is no `get_analyzer` in `utils.py` and  `get_analyzer` is not used in `build_es.py` and `es_search_multi.py`.)

Thanks.

**Comment by AkariAsai** [comment]
Thanks for the heads up! I found the code and README are not updated and fixed the issue in the most recent commits to the [bm25](https://github.com/AkariAsai/XORQA/tree/main/baselines/bm25) directory. Please let me know if you find any issues!

**Comment by tomohideshibata** [comment]
Thank you for fixing the issue. It seems good!
