### ISSUE TITLE
Reader training using dpr baseline

### ISSUE THREAD

**Issue by ffaisal93** [AkariAsai/XORQA#5]
Hello,
For the reader training using dpr baseline, do we need to follow the same process as retrieval training...means:
first, we need to train the reader on orginal nq data and then, train the reader on xorqa data?

or, just training on the xorqa data is enough for the reader part here?

Thanks

**Comment by AkariAsai** [comment]
Hi @ffaisal93, thank you for asking the question! 
We train the multilingual-bert based reader model on Natural Questions data first using publicly available reader training data, and then train the model on XOR-TyDi QA data. We haven't evaluated the model's performance w/o NQ training, so I am not sure if training on XOR QA is enough or not...

**Comment by AkariAsai** [comment]
I'm closing this issue but feel free to re-open if you have any follow-up questions
