### ISSUE TITLE
Corpus used for XOR-Retrieve experiments?

### ISSUE THREAD

**Issue by thakur-nandan** [AkariAsai/XORQA#7]
Hi @AkariAsai, 

First of all, thank you for this amazing work and nice repository.

I was confused regarding which English Wikipedia corpus was utilized for XOR-Retrieve experiments in the paper. 
Is there a pre-processed version of the English Wikipedia corpus available which I can use for evaluation for the XOR-Retrieve task?

Is it this one: https://nlp.cs.washington.edu/xorqa/XORQA_site/data/models/enwiki_20190201_w100.tsv? 

Kind Regards,
Nandan Thakur

**Comment by AkariAsai** [comment]
Hi, @thakur-nandan thank you for contacting us! That link you mentioned should be the version we used for the XOR-retrieval task. 

In particular, we use the English Wikipedia dump listed in [the TyDi QA repository](https://github.com/google-research-datasets/tydiqa#source-data). 
To make the w100 corpus, we simply split each article into 100 tokens as in the original DPR implementation. We also remove the articles that are too short. Please feel free to contact us if you have any questions!

**Comment by thakur-nandan** [comment]
Hi @AkariAsai, Thank you for the prompt response. I got it.

Another small question: Do you include each Wikipedia passage title for evaluation using XOR-Retrieval task? Or are the retrieved passages (100 tokens each) evaluated without title?

Kind Regards,
Nandan Thakur

**Comment by AkariAsai** [comment]
@thakur-nandan No problem! 

> Do you include each Wikipedia passage title for evaluation using XOR-Retrieval task? Or are the retrieved passages (100 tokens each) evaluated without title

During the original evaluation, we only check if the paragraph context itself includes the answer string or not. For example, given the retrieval outputs from DPR formatted as `[{"id": 1234, "title": "Tokyo", "text" : "Tokyo is ..."}]`, we only use the `text` field to form the `ctxs` input for [the evaluation script](https://github.com/AkariAsai/XORQA/blob/main/evals/eval_xor_retrieve.py#L24).

**Comment by thakur-nandan** [comment]
Thank you @AkariAsai!
